### PR TITLE
Fixes #782 | translation font size change not reflecting

### LINKED ISSUE #782: Translation font-size change needs  page refresh
I can resize arabic text, but translation font-size needs to page refresh. Does not work like arabixc font-size.

image

### PR DESCRIPTION
**Pull request by AadilMehrajBhat**
### Summary
The translations font size change isn't reflecting while changing the font size from the settings drawer

### Screenshots

| Before | After |
| ------ | ------ |
| [image here] | [image here] |

### CODE REVIEW

**Comment by muhajirdev** [comment]
awesome, this seemss to fix the issue.

File: src/components/QuranReader/utils/memoization.ts [hunk 1]
```diff
@@ -30,7 +32,7 @@ export const verseFontChanged = (
   prevWords: Word[],
   nextWords: Word[],
 ): boolean =>
-  prevQuranStyles.mushafLines !== nextQuranStyles.mushafLines ||
+  !isEqual(prevQuranStyles, nextQuranStyles) ||
```
Comment (osamasayed) [inline src/components/QuranReader/utils/memoization.ts:35]: using `isEqual` is a great solution but I have 2 comments:

1. We try to stay away from using packages as much as possible if the same can be easily achieved manually.
2. Comparing the entire `quranStyles` object would result in un-necessary re-renders even if the changes are not related to the translation view e.g. changing the Tafsir font while the user is viewing translation will cause every word in the translation view to re-render. You can check the profiler snapshot below for the case of changing the Tafsir font, while viewing the translations, all verses re-rendered:

Screen Shot 2021-11-21 at 09 00 07

so I suggest targeting only the translation font `prev` and `next` and doing the comparison inside `TranslationViewCell.areVersesEqual` because the translation font change is only related to the translation view and not the reading view. JazakAllah Khairan

**Review by osamasayed — CHANGES_REQUESTED** [review]

File: src/components/QuranReader/utils/memoization.ts (hunk 1 above)
Comment (AadilMehrajBhat) [reply src/components/QuranReader/utils/memoization.ts]: @osamasayed Jazakallahu khair for review the PR, I have update the PR as suggested. I have added a separate helper `verseTranslationFontChanged` similar to `verseFontChanged` for comparing the translation font style changes. Do let me know WDYT? 

Shukran

**Review by osamasayed — APPROVED** [review]

File: src/components/QuranReader/utils/memoization.ts (hunk 1 above)
Comment (osamasayed) [reply src/components/QuranReader/utils/memoization.ts]: Looks great to me and good to merge! thanks a lot!
